---
type: wan_rr

wan_path_groups:
  - name: mpls_path
    id: 1001
  - name: internet_path
    id: 1002
  - name: mpls_path2
    id: 1005
  - name: internet_path2
    id: 1006

wan_carriers:
  - name: mpls
    path_group: mpls_path
    trusted: true
  - name: internet
    path_group: internet_path
    trusted: true
  - name: mpls2
    path_group: mpls_path2
    trusted: true
  - name: internet2
    path_group: internet_path2
    trusted: true

wan_rr:
  defaults:
    data_plane_cpu_allocation_max: 1
    loopback_ipv4_pool: 10.99.101.0/24
    vtep_loopback_ipv4_pool: 10.99.102.0/24
    filter:
      always_include_vrfs_in_tenants: [TENANT_A]
  nodes:
    - name: RR1
      id: 1
      cv_pathfinder_region: REGION1
      l3_interfaces:
        - name: Ethernet2
          ip_address: 192.15.71.2/24
          wan_carrier: mpls
        - name: Ethernet3
          ip_address: 192.16.71.2/24
          wan_carrier: internet
    - name: RR2
      id: 2
      cv_pathfinder_region: REGION1
      l3_interfaces:
        - name: Ethernet2
          ip_address: 192.15.72.2/24
          wan_carrier: mpls
        - name: Ethernet3
          ip_address: 192.16.72.2/24
          wan_carrier: internet
    - name: RR3
      id: 3
      cv_pathfinder_region: REGION2
      l3_interfaces:
        - name: Ethernet2
          ip_address: 192.25.76.2/24
          wan_carrier: mpls2
        - name: Ethernet3
          ip_address: 192.26.76.2/24
          wan_carrier: internet2
    - name: RR4
      id: 4
      cv_pathfinder_region: REGION2
      l3_interfaces:
        - name: Ethernet2
          ip_address: 192.25.77.2/24
          wan_carrier: mpls2
        - name: Ethernet3
          ip_address: 192.26.77.2/24
          wan_carrier: internet2