wan_route_servers:
  - hostname: RR1
  - hostname: RR2


overlay_rt_type:
  admin_subfield: bgp_as
tenants:
  - name: TENANT_A
    vrfs:
      - name: default
        vrf_vni: 101
      - name: VRF_A
        vrf_vni: 102


wan_virtual_topologies:
  vrfs:
    - name: VRF_A
      policy: DEFAULT-AVT-POLICY
      wan_vni: 101
  policies:
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [mpls_path, internet_path]
            preference: preferred


wan_path_groups:
  - name: mpls_path
    id: 1001
  - name: internet_path
    id: 1002
  - name: mpls_global_path
    id: 1003
  - name: internet_global_path
    id: 1004
  - name: mpls_path2
    id: 1005
  - name: internet_path2
    id: 1006

wan_carriers:
  - name: mpls
    path_group: mpls_path
    trusted: true
  - name: internet
    path_group: internet_path
    trusted: true
  - name: mpls_global
    path_group: mpls_global_path
    trusted: true
  - name: internet_global
    path_group: internet_global_path
    trusted: true


