overlay_rt_type:
  admin_subfield: bgp_as
tenants:
  - name: TENANT_A
    vrfs:
      - name: default
        vrf_vni: 101
      - name: VRF_A
        vrf_vni: 102


wan_virtual_topologies:
  vrfs:
    - name: VRF_A
      policy: DEFAULT-AVT-POLICY
      wan_vni: 101
  policies:
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [mpls_r1_path, internet_path]
            preference: preferred



