wan_route_servers:
  - hostname: RR3
  - hostname: RR4


cv_pathfinder_regions:
  - name: REGION1
    id: 1
    sites:
      - name: SITE11
        id: 101
      - name: SITE12
        id: 102
      - name: SITE13
        id: 103
      - name: SITE14
        id: 104
      - name: TRANSIT1
        id: 199
  - name: REGION2
    id: 2
    sites:
      - name: SITE21
        id: 201
      - name: SITE22
        id: 202
      - name: SITE23
        id: 203
      - name: SITE24
        id: 204
      - name: TRANSIT2
        id: 299

overlay_rt_type:
  admin_subfield: bgp_as
tenants:
  - name: TENANT_A
    vrfs:
      - name: default
        vrf_vni: 101
      - name: VRF_A
        vrf_vni: 102


wan_virtual_topologies:
  vrfs:
    - name: VRF_A
      policy: DEFAULT-AVT-POLICY
      wan_vni: 101
  policies:
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [mpls_path2, internet_path2]
            preference: preferred


wan_path_groups:
  - name: mpls_path
    id: 1001
  - name: internet_path
    id: 1002
  - name: mpls_global_path
    id: 1003
  - name: internet_global_path
    id: 1004
  - name: mpls_path2
    id: 1005
  - name: internet_path2
    id: 1006

wan_carriers:
  - name: mpls2
    trusted: true
    path_group: mpls_path2
  - name: internet2
    trusted: true
    path_group: internet_path2
  - name: mpls_global
    path_group: mpls_global_path
    trusted: true
  - name: internet_global
    path_group: internet_global_path
    trusted: true
